#!/usr/bin/env python3
from pathlib import Path

path = Path("scripts/build-person-crosswalk.py")
text = path.read_text(encoding="utf-8")

replacements = {
'''REVIEWED_NAME_VARIANTS = {\n    "paul d richardson": {''': '''REVIEWED_NAME_VARIANTS = {\n    "paul richardson": {\n        "canonical_candidate": "paul richardson",\n        "canonical_display_name": "Paul Richardson",\n        "evidence_receipt": "sources/raw/identity/reviewed-name-variants-batch4-2026-09-04.json",\n        "note": "User-reviewed identity resolution: Paul D. Richardson and Paul Richardson are the same person. This is a person-specific decision only.",\n    },\n    "paul d richardson": {''',
'''    "mark a rowden": {''': '''    "mark rowden": {\n        "canonical_candidate": "mark rowden",\n        "canonical_display_name": "Mark Rowden",\n        "evidence_receipt": "sources/raw/identity/reviewed-name-variants-batch4-2026-09-04.json",\n        "note": "User-reviewed identity resolution: Mark A. Rowden and Mark Rowden are the same person. This is a person-specific decision only.",\n    },\n    "mark a rowden": {''',
'''    "stephen thomas estock": {''': '''    "stephen estock": {\n        "canonical_candidate": "stephen estock",\n        "canonical_display_name": "Stephen Estock",\n        "evidence_receipt": "sources/raw/identity/reviewed-name-variants-batch4-2026-09-04.json",\n        "note": "User-reviewed identity resolution: Stephen Thomas Estock and Stephen Estock are the same person. This is a person-specific decision only.",\n    },\n    "stephen thomas estock": {''',
'''    "larry c hoop": {''': '''    "larry hoop": {\n        "canonical_candidate": "larry hoop",\n        "canonical_display_name": "Larry Hoop",\n        "evidence_receipt": "sources/raw/identity/larry-larry-c-hoop-resolution-2026-09-04.json",\n        "note": "User-reviewed identity resolution: Larry C. Hoop and Larry Hoop are the same person. This person-specific decision does not create a general middle-initial matching rule.",\n    },\n    "larry c hoop": {''',
}
for old, new in replacements.items():
    if old not in text:
        raise SystemExit(f"missing expected variant insertion anchor: {old!r}")
    text = text.replace(old, new, 1)

old = '''    elif len(exact_seed_ids) == 1 and len(families) >= 2 and (presbytery_support or institution_support):\n        canonical_id = next(iter(exact_seed_ids))\n        status, method, confidence = "context_confirmed", "seed_name_plus_shared_context", 0.97\n        support.append("exact seed-person name")\n        note = "Exact reviewed seed name plus context repeated in independent source families."\n    elif len(exact_seed_ids) > 1:\n        status, method, confidence = "collision", "duplicate_seed_name", 0.0\n        conflicts.append("multiple seed people have the same normalized name")\n        note = "Requires manual review; no ID assigned."\n    elif variant_conflict:\n'''
new = '''    elif any(r.get("reviewed_name_variant") for r in rows):\n        reviewed = next(r["reviewed_name_variant"] for r in rows if r.get("reviewed_name_variant"))\n        preferred = reviewed["canonical_display_name"]\n        if len(exact_seed_ids) > 1:\n            status, method, confidence = "collision", "duplicate_seed_name", 0.0\n            conflicts.append("multiple seed people have the same normalized name")\n            note = "Requires manual review; no ID assigned."\n        elif len(exact_seed_ids) == 1:\n            canonical_id = next(iter(exact_seed_ids))\n            status, method, confidence = "context_confirmed", "documented_reviewed_identity", 0.99\n            support.append("explicit reviewed person-specific identity equivalence")\n            note = reviewed["note"]\n        else:\n            candidate_id = slug(preferred)\n            if candidate_id in used_ids:\n                status, method, confidence = "collision", "generated_id_collision", 0.0\n                conflicts.append(f"generated ID {candidate_id} is already in use")\n                note = "Requires manual review; no ID assigned."\n            else:\n                canonical_id = candidate_id\n                used_ids.add(candidate_id)\n                status, method, confidence = "context_confirmed", "documented_reviewed_identity", 0.99\n                support.append("explicit reviewed person-specific identity equivalence")\n                note = reviewed["note"]\n                generated_people.append({\n                    "id": canonical_id,\n                    "name": preferred,\n                    "ordination": infer_ordination(rows),\n                    "current_role": None,\n                    "current_organization": None,\n                    "denominational_status": "PCA-related role documented in tracked sources; current status not assessed",\n                    "current_role_source_ids": [],\n                    "profile_status": "identity_crosswalk",\n                })\n    elif len(exact_seed_ids) == 1 and len(families) >= 2 and (presbytery_support or institution_support):\n        canonical_id = next(iter(exact_seed_ids))\n        status, method, confidence = "context_confirmed", "seed_name_plus_shared_context", 0.97\n        support.append("exact seed-person name")\n        note = "Exact reviewed seed name plus context repeated in independent source families."\n    elif len(exact_seed_ids) > 1:\n        status, method, confidence = "collision", "duplicate_seed_name", 0.0\n        conflicts.append("multiple seed people have the same normalized name")\n        note = "Requires manual review; no ID assigned."\n    elif variant_conflict:\n'''
if old not in text:
    raise SystemExit("missing resolver insertion anchor")
text = text.replace(old, new, 1)

path.write_text(text, encoding="utf-8")
