#!/usr/bin/env python3
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(sys.argv[1] if len(sys.argv) > 1 else '.').resolve()


def load(path: str):
    return json.loads((ROOT / path).read_text(encoding='utf-8'))


def write(path: str, value) -> None:
    (ROOT / path).write_text(json.dumps(value, indent=2, ensure_ascii=False) + '\n', encoding='utf-8')


members = load('sources/normalized/national-partnership/confirmed-memberships-canonical.json')['confirmed_members']
people = load('data/people.json')
affiliations = load('data/affiliations.json')

people_ids = {row['id'] for row in people}
canonical_members = {
    row['normalized_person_id']: row
    for row in members
    if row.get('normalized_person_id')
}
missing_people = sorted(set(canonical_members) - people_ids)
if missing_people:
    raise SystemExit(f'canonical NP ids missing from data/people.json: {missing_people}')

GENERATED_NOTE = (
    'Generated from the reviewed canonical National Partnership membership roster. '
    'Exact archival receipts remain in sources/normalized/national-partnership/'
    'confirmed-memberships-canonical.json; this edge records membership only and '
    'does not infer positions on unrelated issues.'
)

# Reconcile only edges generated by this script. Richer manually curated NP edges
# retain their existing role/confidence/source wording and always take precedence.
kept = []
removed_stale = 0
for edge in affiliations:
    is_generated = (
        edge.get('target_type') == 'organization'
        and edge.get('target_id') == 'national-partnership'
        and edge.get('notes') == GENERATED_NOTE
    )
    if is_generated and edge.get('person_id') not in canonical_members:
        removed_stale += 1
        continue
    kept.append(edge)
affiliations = kept

np_by_person: dict[str, list[dict]] = {}
for edge in affiliations:
    if edge.get('target_type') == 'organization' and edge.get('target_id') == 'national-partnership':
        np_by_person.setdefault(edge.get('person_id'), []).append(edge)

created = 0
for person_id in sorted(canonical_members):
    existing = np_by_person.get(person_id, [])
    if len(existing) > 1:
        raise SystemExit(f'duplicate app-facing NP affiliations for {person_id}')
    if existing:
        continue

    edge_id = f'aff-{person_id}-np'
    if any(row.get('id') == edge_id for row in affiliations):
        raise SystemExit(f'affiliation id collision: {edge_id}')
    edge = {
        'id': edge_id,
        'person_id': person_id,
        'target_type': 'organization',
        'target_id': 'national-partnership',
        'role': 'Member',
        'confidence': 'confirmed',
        'evidence_kind': 'network_membership',
        'weight': 4,
        'score_included': True,
        'source_ids': ['src-np-local-archive', 'src-np-index'],
        'notes': GENERATED_NOTE,
    }
    affiliations.append(edge)
    np_by_person[person_id] = [edge]
    created += 1

# Every canonically resolved NP member must now have exactly one app edge.
missing_edges = sorted(set(canonical_members) - set(np_by_person))
duplicates = sorted(pid for pid, edges in np_by_person.items() if pid in canonical_members and len(edges) != 1)
if missing_edges or duplicates:
    raise SystemExit(f'NP projection incomplete: missing={missing_edges}, duplicates={duplicates}')

write('data/affiliations.json', affiliations)
print(json.dumps({
    'canonical_np_people': len(canonical_members),
    'app_np_people': len(set(np_by_person) & set(canonical_members)),
    'created_affiliations': created,
    'removed_stale_affiliations': removed_stale,
}, indent=2))
